  export const REQUEST_PETS = 'REQUEST_PETS';
  export const REQUEST_PETS_FAILURE = 'REQUEST_PETS_FAILURE';

  export const FETCH_PETS_SUCCESS = 'FETCH_PETS_SUCCESS';
  export const GET_PET_SUCCESS = 'GET_PET_SUCCESS';
  export const CREATE_PET_SUCCESS = 'CREATE_PET_SUCCESS';
  export const UPDATE_PET_SUCCESS = 'UPDATE_PET_SUCCESS';
  export const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
